### ISSUE TITLE
runState in resultsCapturer not initialised on Windows 10

### ISSUE THREAD

**Issue by astondg** [mattfritz/protractor-cucumber-framework#43] opened 2016-07-21 03:11 UTC
I'm using protractor-cucumber-framework and grunt-protractor-runner to run BDD tests from a grunt task and I'm getting the following error on Windows 10 only (the same set up runs on OSX).

> node_modules\protractor-cucumberframework\lib\resultsCapturer.js:22
>  state.results.failedCount = 0;
>TypeError: node_modules\protractor-cucumber-framework\lib\resultsCapturer.js:31 Cannot set property 'failedCount' of undefined

Initial investigation suggests that the instance of `runState` that is given to, and initialised in, `index.js` is not the same one given to `resultsCapturer.js` and hence the latter is uninitialised. E.g. if I add `console.log('state exists: ' + Math.random());` to `runState.js` I see this log twice on Windows, each with a different random number, but only once on OSX.

Environment:
Windows 10 Pro - Insider Preview - Version 1607 - Build 14390
NodeJS v6.1.0
grunt-protractor-runner v3.2.0
protractor-cucumber-framework v0.6.0
The protractor config is quite long. I can provide if needed but the it begins with:
`{
  directConnect: true,
  framework: 'custom',
  frameworkPath: 'node_modules/protractor-cucumber-framework',`

**Comment by mattfritz** [comment] 2016-07-21 16:32
It's strange that the `require` cache is invalidated.. Thanks for the detailed report!

Couple questions... what shell are you running this from? Also, because `grunt-protractor-runner` modifies command line arguments as well, would you mind running it with the stock `protractor` command to rule that out?

I don't have a Windows machine to test on, but I'm glad to help. Let me know what I can do

**Comment by leosvelperez** [comment] 2016-07-22 17:48
@mattfritz I'm having the exact same issue by running it mannually with just `protractor protractor.conf.js`. The tests are running fine on a Windows Server 2008 R2 machine, but not on a Windows 10 one. Here is my full protractor.conf.js and below is the failing environment:
```javascript
exports.config = {
    allScriptsTimeout: 11000,
    specs: [
        "./client/e2e/**/*.feature"
    ],
    capabilities: {
        "browserName": "chrome"
    },
    directConnect: true,
    baseUrl: "https://localhost:443/",
    framework: "custom",
    frameworkPath: require.resolve("protractor-cucumber-framework"),
    cucumberOpts: {
        require: [
            "client/e2e/support/env.js",
            "client/e2e/**/*.steps.ts"
        ],
        format: "pretty",
        compiler: "ts:ts-node/register"
    },
    useAllAngular2AppRoots: true,
    onPrepare: function () {
        browser.ignoreSynchronization = false;
        process.env.NODE_ENV = browser.params.env;
    }
};
```
Environment:
Windows 10 Enterprise - Insider Preview  - Build 14393
NodeJS v6.1.0
protractor-cucumber-framework v0.6.0

**Comment by leosvelperez** [comment] 2016-07-22 18:18
@mattfritz I uninstalled NodeJS 6.1.0 and then installed NodeJS 4.4.7 and then tests are working correctly.

**Comment by astondg** [comment] 2016-07-24 22:54
@mattfritz I was running in PowerShell but it seems this is reproducable, thanks @leosvelperez. So is this a NodeJS bug? Or breaking change from v4 to v6? I'm looking through issues and release notes in the NodeJS repo but I haven't found anything to point to either.

**Comment by mattfritz** [comment] 2016-07-25 16:46
I think this is related to https://github.com/nodejs/node/issues/6978, which is caused by https://github.com/nodejs/node/issues/7175, and is discussed in a post-mortem in https://github.com/nodejs/CTC/issues/9... Short term, it's probably not good to use NodeJS version 6 until the problem is resolved.

I'm going to close this for now since it is more than likely related to a NodeJS file path issue. Let me know if you have more information indicating a problem with this framework implementation and I will reopen this issue to investigate.

**Closed by mattfritz** 2016-07-25 16:46 UTC
Labels: question
